import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/ui/footer";
import Header from "@/components/ui/header";
import Hero from "@/components/ui/home/hero";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="">
			<body className={`antialiased leading-6`}>
				<Header>
					<Hero />
				</Header>
				{children}
				<Footer></Footer>
			</body>
		</html>
	);
}
